project:
  type: website

website:
  title: "Website"
  navbar:
   left:
      - text: "Home"
        file: index.qmd
      - Portfolio.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

